# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure-Abonnement 1(d8cd2f9e-2816-4fe8-b17e-82f9204cab2e)'
    subscriptionId: 'd8cd2f9e-2816-4fe8-b17e-82f9204cab2e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test_RG'
    location: 'Germany West Central'
    templateLocation: 'Linked artifact'
    csmFile: 'book-templates/Chapter 03/03-03-00.json'
    csmParametersFile: 'book-templates/Chapter 03/03-02-05.parameters.prod.json'
    deploymentMode: 'Incremental'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest



- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure-Abonnement 1(d8cd2f9e-2816-4fe8-b17e-82f9204cab2e)'
    subscriptionId: 'd8cd2f9e-2816-4fe8-b17e-82f9204cab2e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test_RG'
    location: 'Germany West Central'
    templateLocation: 'Linked artifact'
    csmFile: 'book-templates/Chapter 03/03-03-00.json'
    csmParametersFile: 'book-templates/Chapter 03/03-02-05.parameters.prod.json'
    deploymentMode: 'Incremental'